-- noinspection SqlNoDataSourceInspectionForFile
INSERT INTO role (id, name) VALUES (1, 'DEVELOPER');
INSERT INTO role (id, name) VALUES (2, 'SYSTEMS ANALYST');
INSERT INTO role (id, name) VALUES (3, 'QA ANALYST');
INSERT INTO role (id, name) VALUES (4, 'PROJECT MANAGER');
INSERT INTO role (id, name) VALUES (5, 'TRAINEE');

INSERT INTO DISABILITY (id, name) VALUES (1, 'BLINDNESS');
INSERT INTO DISABILITY (id, name) VALUES (2, 'AUTISM');
INSERT INTO DISABILITY (id, name) VALUES (3, 'DEAFNESS');
INSERT INTO DISABILITY (id, name) VALUES (4, 'DUMBNESS');
INSERT INTO DISABILITY (id, name) VALUES (5, 'WHEELCHAIR');