-- noinspection SqlNoDataSourceInspectionForFile
INSERT INTO role (id, name, salary) VALUES (1, 'DEVELOPER', 6500.00);
INSERT INTO role (id, name, salary) VALUES (2, 'SYSTEMS ANALYST', 7000.00);
INSERT INTO role (id, name, salary) VALUES (3, 'QA ANALYST', 4500.00);
INSERT INTO role (id, name, salary) VALUES (4, 'PROJECT MANAGER', 8500.00);
INSERT INTO role (id, name, salary) VALUES (5, 'TRAINEE', 2000.00);

INSERT INTO DISABILITY (id, name) VALUES (1, 'BLINDNESS');
INSERT INTO DISABILITY (id, name) VALUES (2, 'AUTISM');
INSERT INTO DISABILITY (id, name) VALUES (3, 'DEAFNESS');
INSERT INTO DISABILITY (id, name) VALUES (4, 'DUMBNESS');
INSERT INTO DISABILITY (id, name) VALUES (5, 'WHEELCHAIR');